#In this file you can specify to how many vwarps will have access different ranks, how long player will wait for teleport and where vwarps can be create.
#For example if you want to have VIP access for two and SVIP, for four, write it like this:
#VIP: 2
#SVIP: 4
#It's really simple.
#If a group is not located here, it will not be able to set any vwarp.


#Here you can type how many seconds user must wait before teleport.
#Please be sure that number is integer, greater than zero. If you type wrong number, plugin will use default delay time which is equals 3 seconds.
delay: 

#Here you can type list of groups who can teleport without waiting.
#Every group is typed in another line, like this:
# - Group1
# - Group2
groups:
    
#Here you can define if you want use vwarps only in one world or on whole server.
#If you type true, you must define names of worlds in list under label name:
only_one_world: false
name:
    