name: vWarp
author: NRUB
main: vwarp.VWarp
version: 3.11.2
description: Simply and safe warps for players.

commands:
    vwarp:
        description: teleporting to the desired vwarp
        usage: /<command> [nick] lub /<command> [nick] [nr]
        permission: vwarp.vwarp
        permission-message: You do not have sufficient permission!
    setvwarp:
        description: setting of vwarp
        usage: /<command> lub /<command> [nr]
        permission: vwarp.setvwarp
        permission-message: You do not have sufficient permission!
    delvwarp:
        description: removing of vwarp
        usage: /<command> lub /<command> [nr]
        permission: vwarp.delvwarp
        permission-message: You do not have sufficient permission!
    asetvwarp:
        description: setting of vwarp for user by the administrator
        usage: /<command> [nick] lub /<command> [nick] [nr]
        permission: vwarp.asetvwarp
        permission-message: You do not have sufficient permission!
    adelvwarp:
        description: removing of vwarp for user by the administrator
        usage: /<command> [nick] lub /<command> [nick] [nr]
        permission: vwarp.adelvwarp
        permission-message: You do not have sufficient permission!
    vwarps:
        description: showing list of all vwarps
        usage: /<command> [page nr]
        permission: vwarp.vwarps
        permission-message: You do not have sufficient permission!
    vreload:
        description: reload plugin and configs
        usage: /<command>
        permission: vwarp.vreload
        permission-message: You do not have sufficient permission!
    vrepair:
        description: load and overwrite list of all vwarps
        usage: /<command>
        permission: vwarp.vrepair
        permission-message: You do not have sufficient permission!
    vlist:
        description: showing list of all backups
        usage: /<command>
        permission: vwarp.vlist
        permission-message: You do not have sufficient permission!
    vbackuprestore:
        description: restoring selected backup
        usage: /<command> [date and time]
        permission: vwarp.vbackuprestore
        permission-message: You do not have sufficient permission!
    vupdate:
        description: forcing update plugin
        usage: /<command>
        permission: vwarp.vupdate
        permission-message: You do not have sufficient permission!

permisions:
    vwarp:
        default: true
    setvwarp:
        default: false
    delvwarp:
        default: false
    asetvwarp:
        default: false
    adelvwarp:
        default: false
    vwarps:
        default: true
    vreload:
        default: false
    vrepair:
        default: false
    vlist:
        default: false
    vbackuprestore:
        default: false
    vupdate:
        defualt: false